### ISSUE TITLE
Lambda 関数内で経過時間を取得する

### ISSUE THREAD

**Issue by hassaku63** [serverless-operations/jeffy-ja#2]
3rd party の外部APIを呼ぶ場合、レスポンスが戻る前に Lambda 自身の Timeout が来てしまい、ハンドルされないエラーが発生してしまうケースがあります。

3rd party API の Timeout を Lambda 自身の Timeout より短くなるようにクライアント側でコントロールする必要がありますが、適切にハンドリングするためにはそのAPIを呼び出す時点での lambda invocation time の残り時間を知る必要があります。

# 解決方針

- handlers のデコレータの共通処理として、実行時間の計測処理を挟む
- app インスタンスのメソッドに現時点までの実行時間を返す `elapsed_time` メソッドもしくはプロパティを追加する

Invocation Timeout の値は Serverless Framework 等で環境変数を渡すなど、デプロイツール側で適切な実装を行っている必要があります。そのため、残り時間を直接算出する機能を jeffy でやる必要はなく、経過時間を提供する機能があると良いと考えます。

**Comment by hassaku63** [comment]
https://docs.aws.amazon.com/lambda/latest/dg/python-context.html

公式ドキュメントを確認したところ、 `context. get_remaining_time_in_millis()` で必要なインタフェースは提供されていました。

issue の主旨は解消されたのでクローズします。

**Comment by horike37** [comment]
解決したとのことでよかったです！issue立ててもらってありがとうございました 👍
